### ISSUE TITLE
ImageProcessing gem hangs in GitHub Actions CI

### ISSUE THREAD

**Issue by rodrigoargumedo** [janko/image_processing#128]
Hi,

I was doing some research why the image_processing gem was causing to hang and having it to fail after 6 hours of running the GitHub Actions runner container.

```yml
        ...
       - name: Install vips
          run: |
            sudo apt-get update
            sudo apt-get install -y libvips
       - name: Run tests
         run: bundle exec rails test
      ...
```

Rails tries to invoke the `image_processing` gem with following resource that I made in test for sampling purposes:

```ruby
setup do
  @account = accounts(:one)
  ...
end

test 'avatar attached' do
  @account.avatar.attach(io: File.open('test/fixtures/files/test.png', filename: 'test.png')
  assert @account.avatar.variant(resize: '100x100')
end
```

However, version 1.13.x broke GitHub Actions CI runner and causing a lot of headaches and issues for those who updated to this version. The only workaround I found is by downgrading to version 1.12.2 and additionally adding `image_magick` to the stack and temporarily resolves the problem.

Before:
![Before Source](https://github.com/user-attachments/assets/009662d9-3345-4a1f-9cf0-531806870d82)

After:
![After Source](https://github.com/user-attachments/assets/ce483e60-ed0e-455f-9a1e-6b1430168c2a)

Is there a permanent solution to this issue?
